### ISSUE TITLE
setup fails to read xpub from public.txt generated by coldcard q

### ISSUE THREAD

**Issue by alexmat** [jamesob/coldcore#62]
```
 ◰  waiting for public.txt 
 !  error parsing public.txt contents
 !  check your public.txt file and try this again, or file a bug:
 !    github.com/jamesob/coldcore/issues

Traceback (most recent call last):
  File "./coldcore", line 980, in run_setup
    wallet = CCWallet.from_io(io.StringIO(pubfile.read_text()), rpc)
  File "./coldcore", line 2432, in from_io
    raise ValueError("couldn't find xpub path")
ValueError: couldn't find xpub path
```

relevant section of public.txt

```
## Top-level, 'master' extended public key ('m/'):

xpub***

What follows are derived public keys and payment addresses, as may
be needed for different systems.


## For BIP-44 / Electrum: m/44h/0h/{account}h/{change}/{idx}

First 5 receive addresses (account=0, change=0):

m/44h/0h/0h => xpub***

## For BIP-49 (P2WPKH-nested-in-P2SH): m/49h/0h/{account}h/{change}/{idx}

First 5 receive addresses (account=0, change=0):

m/49h/0h/0h => xpub***
m/49h/0h/0h => ypub***

## For BIP-84 (Native Segwit P2WPKH): m/84h/0h/{account}h/{change}/{idx}

First 5 receive addresses (account=0, change=0):

m/84h/0h/0h => xpub***
m/84h/0h/0h => zpub***   ##SLIP-132##
m/84h/0h/0h/0/0 => ...
```

**Comment by jamesob** [comment]
Thanks for the report - I'm working on getting a Q so I can implement this.

**Comment by jamesob** [comment]
@alexmat sorry it took a while, but this should be fixed. Let me know if you have any issues.
